config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins

  namespace :admin do
    resources :admins
  end

  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin/admins_controller.rb
# frozen_string_literal: true

class Admin
  class AdminsController < ApplicationController
    before_action :authenticate_admin!

    def index
      @current_admin = current_admin.email
    end

    def show
      @admins = Admin.find(params[:id])
    end

    def edit
      @admin = Admin.find(params[:id])
    end

    def update
      @admin = Admin.find(params[:id])

      if @admin.update(admin_params)
        redirect_to department_admins_path(@admin)
      else
        render :edit
      end
    end

    private

      def admin_params
        params.require(:admin).permit(:name)
      end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/admin/admins_helper.rb
# frozen_string_literal: true

class Admin
  module AdminsHelper
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AsPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
 -->
  </head>

  <body id="page-top">
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<body class="bg-gradient-primary">

    <div class="container">
      <div class="text-center">
         <div>
             <%= image_tag "",	 class: 'img-circle', width: '20%' %>
         </div>

          <h1 class="text-success"><i><b>Welcome<br> To<br> Howard University </b></i></h1>

            <h3><%= link_to 'Admin', admin_admins_path, class: "text-info" %></h3>

            <h3><%= link_to 'Branch Manager', nil , class: "text-info" %></h3>

            <h3><%= link_to 'Student', nil , class: 'text-info' %></h3><br>

          </div>
        </div>
        <!-- Outer Row -->

    </div>

</body>